# Generated by Django 3.1.4 on 2021-01-11 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookMaster',
            fields=[
                ('BookID', models.AutoField(primary_key=True, serialize=False)),
                ('BookName', models.CharField(help_text='Enter BookName: ', max_length=25)),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('Description', models.CharField(max_length=1000)),
                ('Iscompleted', models.BooleanField(default=0)),
                ('IsActive', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryMaster',
            fields=[
                ('categoryID', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(help_text="what your book's category: ", max_length=25)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('modifiedAt', models.DateTimeField(auto_now=True)),
                ('IsActive', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserTypeMaster',
            fields=[
                ('UserTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('UserType', models.CharField(max_length=255)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('ModifiedAt', models.DateTimeField(auto_now=True)),
                ('IsActive', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(help_text='Enter User Name: ', max_length=25)),
                ('UserPassword', models.CharField(max_length=20)),
                ('UserEmail', models.EmailField(max_length=25, unique=True)),
                ('UserMobile', models.BigIntegerField()),
                ('UserAddress', models.CharField(default='No Address', max_length=255, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('ModifiedAt', models.DateTimeField(auto_now=True)),
                ('IsActive', models.BooleanField(default=1)),
                ('UserTypeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='novel.usertypemaster')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterMaster',
            fields=[
                ('ChapterID', models.AutoField(primary_key=True, serialize=False)),
                ('ChapterData', models.CharField(max_length=5000)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('ModifyAt', models.DateTimeField(auto_now=True)),
                ('IsActive', models.BooleanField(default=1)),
                ('BookID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='novel.bookmaster')),
            ],
        ),
        migrations.AddField(
            model_name='bookmaster',
            name='CategoryID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='novel.categorymaster'),
        ),
        migrations.AddField(
            model_name='bookmaster',
            name='UserID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='novel.usermaster'),
        ),
    ]
