# Generated by Django 3.1.4 on 2021-02-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmaster',
            old_name='Iscompleted',
            new_name='IsCompleted',
        ),
        migrations.RenameField(
            model_name='bookmaster',
            old_name='modifiedDate',
            new_name='ModifiedDate',
        ),
        migrations.AddField(
            model_name='bookmaster',
            name='BookImage',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='chaptermaster',
            name='ChapterName',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='chaptermaster',
            name='ChapterNo',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
