# Generated by Django 3.1.4 on 2021-03-16 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0002_auto_20210203_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymaster',
            old_name='categoryID',
            new_name='CategoryID',
        ),
        migrations.RenameField(
            model_name='categorymaster',
            old_name='categoryName',
            new_name='CategoryName',
        ),
        migrations.RenameField(
            model_name='categorymaster',
            old_name='createdAt',
            new_name='CreatedAt',
        ),
    ]
